### DISCUSSION TITLE
How to override the size of the fields in the template

### DISCUSSION THREAD

**Discussion by jorge-ramirezs** [oscarmcm/django-places#48] [General]
Hello,
I'm creating a new template, the issue is once I display the "location" form in the template, the field for the address is too small.

How can I modify the size for the fields?

in template I'm just passing this

```html
<h5>Dirección</h5>
    {{ form.location }}
    {{ form.media }}
</div>
```

![Screenshot 2023-11-04 at 3 53 16 PM](https://github.com/oscarmcm/django-places/assets/63554124/74df144e-bd63-4dc2-8489-cb2b36d9b5d3)

Thanks!

**Comment by oscarmcm** [comment]
Hey!

Are you rendering the `form.media` in the template?

The other option is to override the css directly in your app styles or in the template:

```css
  .places-widget > input:first-child {
    display: block;
    width: 30%;
    margin-bottom: 10px;
  }
```


Lmk if that solve it.

**Reply by jorge-ramirezs** [reply]
I'm retaking this project, unfortunately this solution is not working.

Yes, I'm rendering the "form.media" in the template as mentioned in my previous message.

I'm adding the css you suggested in my style.css but it's not overriding the class.

Thank you

**Reply by oscarmcm** [reply]
Hey @jorge-ramirezs did you set the `width` to be `100%`?

**Reply by jorge-ramirezs** [reply]
Thank you for your prompt response. As you can imagine I'm not a front developer 🤕 

To your question, yes I did. I took your css from ".venv/lib/python3.11/site-packages/places/static/places/places.css" and copied it to my "static/css/style.css", and modified that line only to make it as this:

```css
.places-widget {
  overflow: hidden;
}
.places-widget > input:first-child {
display: block;
width: 100%;
margin-bottom: 10px;
}
.places-widget > input:nth-child(2) {
margin-right: 10px;
}
.places-widget > div {
border: 1px solid #CACACA;
margin-top: 10px;
}
```

In my browser I can see that "places.css" takes precedence on top of "style.css" and overwrites my changes:

<img width="1582" alt="Screenshot 2024-01-03 at 9 51 31 AM" src="https://github.com/oscarmcm/django-places/assets/63554124/618a921f-a968-4fe5-843f-a70aa514d060">

For testing purposes, if I disable the line "width: 30%" in the "inspect" window, the field expands to 100%.

<img width="1582" alt="Screenshot 2024-01-03 at 9 55 55 AM" src="https://github.com/oscarmcm/django-places/assets/63554124/de6c9f37-ba66-4b2d-b123-d2a897906cb7">

---

By the way, the other test I did was to update the file "places.css" and modify the width to 100% and it worked of course, but I understand this is not the best way, there must be a way to override this value.

Thank you.

**Reply by oscarmcm** [reply]
@jorge-ramirezs Yeah your issue is more related to specificity probably adding an `!important` to the styles in your template will fix it.

**Reply by jorge-ramirezs** [reply]
That makes the trick. Thank you.

**Reply by jorge-ramirezs** [reply]
Adding "!Important" in my style.css solves the issue, now the field is expanded at 100%

```css
.places-widget > input:first-child {
display: block;
width: 100% !important;
margin-bottom: 10px;
}
```
Thank you again!
