### ISSUE TITLE
Place field without map

### ISSUE THREAD

**Issue by zyjswiadomielife** [oscarmcm/django-places#29]
Hi, it's possible to show only Places with autocomplete field in form without map, long and lat field?

**Comment by oscarmcm** [comment]
Hi @zyjswiadomielife currently not out of the box, but I think you can hide the inputs/divs with a proper css styles in the admin form:

```python
@admin.register(MyModel)
class MyModelAdmin(admin.ModelAdmin):
    list_display = ['field_a', 'field_b']
    search_fields = ['field_a', 'field_b']
    
    class Media:
        css = {
            'all': ('css/admin/styles.css',)
         }
```

```css
.places-widget > input, 
.places-widget > div {
    display: none;
}
```
